apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chat-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "chat-ui.selectorLabels" . | nindent 4 }}

# Made with Bob
