apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-workflows.fullname" . }}-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: web
    protocol: TCP
    name: web
  selector:
    {{- include "argo-workflows.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server

# Made with Bob
