{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: nilabja-haldar-dev
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
{{- end }}

# Made with Bob
