apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-query
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: 10901
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "thanos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: query

# Made with Bob
